use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Clone)]
struct ClassDef {
    id: String,
    iri: String,
    label: String,
    definition: Option<String>,
    parent_id: Option<String>,
    variant: String,
}

#[derive(Debug, Clone)]
struct RelationDef {
    id: String,
    iri: String,
    label: String,
    definition: Option<String>,
    inverse_id: Option<String>,
    domain: Option<ClassExpr>,
    range: Option<ClassExpr>,
    symmetric: bool,
    transitive: bool,
    functional: bool,
    inverse_functional: bool,
    variant: String,
}

#[derive(Debug, Clone)]
enum ClassExpr {
    Named(String),
    Union(Vec<ClassExpr>),
    Intersection(Vec<ClassExpr>),
    Complement(Box<ClassExpr>),
}

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let ofn_path = manifest_dir.join("BFO-2020-master/21838-2/owl/bfo-core.ofn");
    println!("cargo:rerun-if-changed={}", ofn_path.display());

    let text = fs::read_to_string(&ofn_path).expect("failed to read bfo-core.ofn");
    let generated = generate(&text);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("generated.rs"), generated).expect("failed to write generated.rs");
}

fn generate(ofn: &str) -> String {
    let class_iris = parse_declarations(ofn, "Declaration(Class(");
    let relation_iris = parse_declarations(ofn, "Declaration(ObjectProperty(");
    let labels = parse_annotation_map(ofn, "AnnotationAssertion(rdfs:label ");
    let definitions = parse_annotation_map(ofn, "AnnotationAssertion(skos:definition ");
    let class_parents = parse_class_parents(ofn);
    let inverses = parse_inverses(ofn);
    let domains = parse_object_property_expr_map(ofn, "ObjectPropertyDomain(");
    let ranges = parse_object_property_expr_map(ofn, "ObjectPropertyRange(");
    let symmetric_relations = parse_property_flags(ofn, "SymmetricObjectProperty(");
    let transitive_relations = parse_property_flags(ofn, "TransitiveObjectProperty(");
    let functional_relations = parse_property_flags(ofn, "FunctionalObjectProperty(");
    let inverse_functional_relations =
        parse_property_flags(ofn, "InverseFunctionalObjectProperty(");

    let mut class_defs = class_iris
        .into_iter()
        .map(|iri| {
            let id = iri_to_bfo_id(&iri);
            let label = labels
                .get(&iri)
                .cloned()
                .unwrap_or_else(|| id_to_fallback_label(&id));
            let variant = sanitize_to_variant(&label);
            ClassDef {
                id: id.clone(),
                iri: iri.clone(),
                label,
                definition: definitions.get(&iri).cloned(),
                parent_id: class_parents.get(&id).cloned(),
                variant,
            }
        })
        .collect::<Vec<_>>();
    class_defs.sort_by(|a, b| a.id.cmp(&b.id));
    assert_unique_variants(class_defs.iter().map(|def| def.variant.as_str()), "class");

    let mut relation_defs = relation_iris
        .into_iter()
        .map(|iri| {
            let id = iri_to_bfo_id(&iri);
            let label = labels
                .get(&iri)
                .cloned()
                .unwrap_or_else(|| id_to_fallback_label(&id));
            let variant = sanitize_to_variant(&label);
            RelationDef {
                id: id.clone(),
                iri: iri.clone(),
                label,
                definition: definitions.get(&iri).cloned(),
                inverse_id: inverses.get(&id).cloned(),
                domain: domains.get(&id).cloned(),
                range: ranges.get(&id).cloned(),
                symmetric: symmetric_relations.contains(&id),
                transitive: transitive_relations.contains(&id),
                functional: functional_relations.contains(&id),
                inverse_functional: inverse_functional_relations.contains(&id),
                variant,
            }
        })
        .collect::<Vec<_>>();
    relation_defs.sort_by(|a, b| a.id.cmp(&b.id));
    assert_unique_variants(relation_defs.iter().map(|def| def.variant.as_str()), "relation");

    let class_variant_by_id = class_defs
        .iter()
        .map(|def| (def.id.clone(), def.variant.clone()))
        .collect::<BTreeMap<_, _>>();
    let relation_variant_by_id = relation_defs
        .iter()
        .map(|def| (def.id.clone(), def.variant.clone()))
        .collect::<BTreeMap<_, _>>();

    let mut output = String::new();
    output.push_str("// @generated by build.rs\n");
    output.push_str("use serde::{Deserialize, Serialize};\n\n");

    output.push_str("#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    output.push_str("pub enum BfoClass {\n");
    for def in &class_defs {
        output.push_str(&format!("    {},\n", def.variant));
    }
    output.push_str("}\n\n");

    output.push_str("impl BfoClass {\n");
    output.push_str("    pub const ALL: &'static [Self] = &[\n");
    for def in &class_defs {
        output.push_str(&format!("        Self::{},\n", def.variant));
    }
    output.push_str("    ];\n\n");
    output.push_str("    pub const fn id(self) -> &'static str {\n        match self {\n");
    for def in &class_defs {
        output.push_str(&format!("            Self::{} => \"{}\",\n", def.variant, def.id));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn iri(self) -> &'static str {\n        match self {\n");
    for def in &class_defs {
        output.push_str(&format!("            Self::{} => \"{}\",\n", def.variant, def.iri));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn label(self) -> &'static str {\n        match self {\n");
    for def in &class_defs {
        output.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            def.variant,
            escape_string(&def.label)
        ));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn definition(self) -> Option<&'static str> {\n        match self {\n");
    for def in &class_defs {
        match &def.definition {
            Some(definition) => output.push_str(&format!(
                "            Self::{} => Some(\"{}\"),\n",
                def.variant,
                escape_string(definition)
            )),
            None => output.push_str(&format!("            Self::{} => None,\n", def.variant)),
        }
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn parent(self) -> Option<Self> {\n        match self {\n");
    for def in &class_defs {
        match &def.parent_id {
            Some(parent_id) => output.push_str(&format!(
                "            Self::{} => Some(Self::{}),\n",
                def.variant,
                class_variant_by_id
                    .get(parent_id)
                    .unwrap_or_else(|| panic!("missing parent variant for {}", parent_id))
            )),
            None => output.push_str(&format!("            Self::{} => None,\n", def.variant)),
        }
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn is_a(self, other: Self) -> bool {\n        match self {\n");
    for def in &class_defs {
        let ancestors = class_ancestor_variants(def, &class_defs, &class_variant_by_id);
        output.push_str(&format!("            Self::{} => match other {{\n", def.variant));
        for ancestor in ancestors {
            output.push_str(&format!("                Self::{} => true,\n", ancestor));
        }
        output.push_str("                _ => false,\n");
        output.push_str("            },\n");
    }
    output.push_str("        }\n    }\n}\n\n");

    output.push_str("#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    output.push_str("pub enum RelationKind {\n");
    for def in &relation_defs {
        output.push_str(&format!("    {},\n", def.variant));
    }
    output.push_str("}\n\n");

    output.push_str("impl RelationKind {\n");
    output.push_str("    pub const ALL: &'static [Self] = &[\n");
    for def in &relation_defs {
        output.push_str(&format!("        Self::{},\n", def.variant));
    }
    output.push_str("    ];\n\n");
    output.push_str("    pub const fn id(self) -> &'static str {\n        match self {\n");
    for def in &relation_defs {
        output.push_str(&format!("            Self::{} => \"{}\",\n", def.variant, def.id));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn iri(self) -> &'static str {\n        match self {\n");
    for def in &relation_defs {
        output.push_str(&format!("            Self::{} => \"{}\",\n", def.variant, def.iri));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn label(self) -> &'static str {\n        match self {\n");
    for def in &relation_defs {
        output.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            def.variant,
            escape_string(&def.label)
        ));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn definition(self) -> Option<&'static str> {\n        match self {\n");
    for def in &relation_defs {
        match &def.definition {
            Some(definition) => output.push_str(&format!(
                "            Self::{} => Some(\"{}\"),\n",
                def.variant,
                escape_string(definition)
            )),
            None => output.push_str(&format!("            Self::{} => None,\n", def.variant)),
        }
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub fn domain_allows(self, class: BfoClass) -> bool {\n        match self {\n");
    for def in &relation_defs {
        let body = def
            .domain
            .as_ref()
            .map(|expr| render_class_expr(expr, &class_variant_by_id))
            .unwrap_or_else(|| "true".to_string());
        output.push_str(&format!("            Self::{} => {},\n", def.variant, body));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub fn range_allows(self, class: BfoClass) -> bool {\n        match self {\n");
    for def in &relation_defs {
        let body = def
            .range
            .as_ref()
            .map(|expr| render_class_expr(expr, &class_variant_by_id))
            .unwrap_or_else(|| "true".to_string());
        output.push_str(&format!("            Self::{} => {},\n", def.variant, body));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn is_symmetric(self) -> bool {\n        match self {\n");
    for def in &relation_defs {
        output.push_str(&format!(
            "            Self::{} => {},\n",
            def.variant, def.symmetric
        ));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn is_transitive(self) -> bool {\n        match self {\n");
    for def in &relation_defs {
        output.push_str(&format!(
            "            Self::{} => {},\n",
            def.variant, def.transitive
        ));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn is_functional(self) -> bool {\n        match self {\n");
    for def in &relation_defs {
        output.push_str(&format!(
            "            Self::{} => {},\n",
            def.variant, def.functional
        ));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn is_inverse_functional(self) -> bool {\n        match self {\n");
    for def in &relation_defs {
        output.push_str(&format!(
            "            Self::{} => {},\n",
            def.variant, def.inverse_functional
        ));
    }
    output.push_str("        }\n    }\n\n");
    output.push_str("    pub const fn inverse(self) -> Option<Self> {\n        match self {\n");
    for def in &relation_defs {
        match &def.inverse_id {
            Some(inverse_id) => output.push_str(&format!(
                "            Self::{} => Some(Self::{}),\n",
                def.variant,
                relation_variant_by_id
                    .get(inverse_id)
                    .unwrap_or_else(|| panic!("missing inverse variant for {}", inverse_id))
            )),
            None => output.push_str(&format!("            Self::{} => None,\n", def.variant)),
        }
    }
    output.push_str("        }\n    }\n}\n");
    output
}

fn parse_declarations(ofn: &str, prefix: &str) -> Vec<String> {
    let mut values = Vec::new();
    for line in ofn.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix(prefix) {
            if let Some(iri) = extract_iri(rest) {
                values.push(iri.to_string());
            }
        }
    }
    values
}

fn parse_annotation_map(ofn: &str, prefix: &str) -> BTreeMap<String, String> {
    let mut values = BTreeMap::new();
    for line in ofn.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix(prefix) else {
            continue;
        };
        let Some(iri) = extract_iri(rest) else {
            continue;
        };
        let Some(value) = extract_quoted_text(trimmed) else {
            continue;
        };
        values.insert(iri.to_string(), value);
    }
    values
}

fn parse_class_parents(ofn: &str) -> BTreeMap<String, String> {
    let mut parents = BTreeMap::new();
    for line in ofn.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("SubClassOf(") else {
            continue;
        };
        let mut iris = extract_all_iris(rest);
        if trimmed.contains("Object") || iris.len() != 2 {
            continue;
        }
        let child = iri_to_bfo_id(&iris.remove(0));
        let parent = iri_to_bfo_id(&iris.remove(0));
        parents.insert(child, parent);
    }
    parents
}

fn parse_inverses(ofn: &str) -> BTreeMap<String, String> {
    let mut inverses = BTreeMap::new();
    for line in ofn.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("InverseObjectProperties(") else {
            continue;
        };
        let iris = extract_all_iris(rest);
        if iris.len() != 2 {
            continue;
        }
        let left = iri_to_bfo_id(&iris[0]);
        let right = iri_to_bfo_id(&iris[1]);
        inverses.insert(left.clone(), right.clone());
        inverses.insert(right, left);
    }
    inverses
}

fn parse_object_property_expr_map(ofn: &str, prefix: &str) -> BTreeMap<String, ClassExpr> {
    let mut values = BTreeMap::new();
    for line in ofn.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix(prefix) else {
            continue;
        };
        let Some(iri) = extract_iri(rest) else {
            continue;
        };
        let Some(end) = rest.find('>') else {
            continue;
        };
        let expr_text = rest[end + 1..].trim();
        let Some(expr_text) = expr_text.strip_suffix(')') else {
            continue;
        };
        values.insert(iri_to_bfo_id(iri), parse_class_expr(expr_text));
    }
    values
}

fn parse_property_flags(ofn: &str, prefix: &str) -> BTreeSet<String> {
    let mut values = BTreeSet::new();
    for line in ofn.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix(prefix) else {
            continue;
        };
        let Some(iri) = extract_iri(rest) else {
            continue;
        };
        values.insert(iri_to_bfo_id(iri));
    }
    values
}

fn parse_class_expr(text: &str) -> ClassExpr {
    let (expr, rest) = parse_class_expr_inner(text.trim());
    if !rest.trim().is_empty() {
        panic!("unexpected trailing class expression tokens: {rest}");
    }
    expr
}

fn parse_class_expr_inner(text: &str) -> (ClassExpr, &str) {
    let text = text.trim_start();
    if let Some(rest) = text.strip_prefix("ObjectUnionOf(") {
        let (items, rest) = parse_class_expr_list(rest);
        return (ClassExpr::Union(items), rest);
    }
    if let Some(rest) = text.strip_prefix("ObjectIntersectionOf(") {
        let (items, rest) = parse_class_expr_list(rest);
        return (ClassExpr::Intersection(items), rest);
    }
    if let Some(rest) = text.strip_prefix("ObjectComplementOf(") {
        let (expr, rest) = parse_class_expr_inner(rest);
        let rest = rest
            .trim_start()
            .strip_prefix(')')
            .expect("ObjectComplementOf should close");
        return (ClassExpr::Complement(Box::new(expr)), rest);
    }
    let end = text
        .find('>')
        .expect("named class expression should contain closing '>'");
    let iri = &text[1..end];
    (ClassExpr::Named(iri_to_bfo_id(iri)), &text[end + 1..])
}

fn parse_class_expr_list(mut text: &str) -> (Vec<ClassExpr>, &str) {
    let mut items = Vec::new();
    loop {
        text = text.trim_start();
        if let Some(rest) = text.strip_prefix(')') {
            return (items, rest);
        }
        let (expr, rest) = parse_class_expr_inner(text);
        items.push(expr);
        text = rest;
    }
}

fn render_class_expr(expr: &ClassExpr, class_variant_by_id: &BTreeMap<String, String>) -> String {
    render_class_expr_with_parens(expr, class_variant_by_id, false)
}

fn class_ancestor_variants(
    def: &ClassDef,
    class_defs: &[ClassDef],
    class_variant_by_id: &BTreeMap<String, String>,
) -> Vec<String> {
    let parent_by_id = class_defs
        .iter()
        .map(|class_def| (class_def.id.as_str(), class_def.parent_id.as_deref()))
        .collect::<BTreeMap<_, _>>();

    let mut ancestors = vec![def.variant.clone()];
    let mut current = def.parent_id.as_deref();
    while let Some(parent_id) = current {
        let variant = class_variant_by_id
            .get(parent_id)
            .unwrap_or_else(|| panic!("missing ancestor variant for {}", parent_id));
        ancestors.push(variant.clone());
        current = parent_by_id.get(parent_id).copied().flatten();
    }
    ancestors
}

fn render_class_expr_with_parens(
    expr: &ClassExpr,
    class_variant_by_id: &BTreeMap<String, String>,
    wrap: bool,
) -> String {
    match expr {
        ClassExpr::Named(id) => format!(
            "class.is_a(BfoClass::{})",
            class_variant_by_id
                .get(id)
                .unwrap_or_else(|| panic!("missing class variant for {}", id))
        ),
        ClassExpr::Union(items) => {
            let parts = items
                .iter()
                .map(|item| render_class_expr_with_parens(item, class_variant_by_id, true))
                .collect::<Vec<_>>();
            let body = parts.join(" || ");
            if wrap { format!("({body})") } else { body }
        }
        ClassExpr::Intersection(items) => {
            let parts = items
                .iter()
                .map(|item| render_class_expr_with_parens(item, class_variant_by_id, true))
                .collect::<Vec<_>>();
            let body = parts.join(" && ");
            if wrap { format!("({body})") } else { body }
        }
        ClassExpr::Complement(item) => {
            format!(
                "!({})",
                render_class_expr_with_parens(item, class_variant_by_id, false)
            )
        }
    }
}

fn extract_iri(text: &str) -> Option<&str> {
    let start = text.find('<')?;
    let end = text[start + 1..].find('>')? + start + 1;
    Some(&text[start + 1..end])
}

fn extract_all_iris(text: &str) -> Vec<String> {
    let mut iris = Vec::new();
    let mut rest = text;
    while let Some(start) = rest.find('<') {
        let after = &rest[start + 1..];
        let Some(end) = after.find('>') else {
            break;
        };
        iris.push(after[..end].to_string());
        rest = &after[end + 1..];
    }
    iris
}

fn extract_quoted_text(text: &str) -> Option<String> {
    let start = text.find('"')?;
    let rest = &text[start + 1..];
    let end = rest.find("\"@")?;
    Some(rest[..end].replace("\\\"", "\""))
}

fn iri_to_bfo_id(iri: &str) -> String {
    let suffix = iri
        .rsplit('/')
        .next()
        .expect("iri should have trailing component");
    suffix.replace('_', ":")
}

fn id_to_fallback_label(id: &str) -> String {
    id.to_lowercase()
}

fn sanitize_to_variant(label: &str) -> String {
    let mut out = String::new();
    for part in label
        .trim()
        .replace('-', " ")
        .replace('/', " ")
        .split_whitespace()
    {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn escape_string(input: &str) -> String {
    input.replace('\\', "\\\\").replace('"', "\\\"")
}

fn assert_unique_variants<'a>(variants: impl Iterator<Item = &'a str>, kind: &str) {
    let mut seen = BTreeSet::new();
    for variant in variants {
        if !seen.insert(variant.to_string()) {
            panic!("duplicate {kind} variant: {variant}");
        }
    }
}
